[build]
builder = "NIXPACKS"
buildCommand = "bun run build"

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[deploy]
startCommand = "bun run start"
